# Generated by Django 5.1.3 on 2024-12-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="inventory",
            field=models.SmallIntegerField(),
        ),
    ]
