# Generated by Django 5.1.3 on 2024-12-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_menu_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="no_of_guests",
            field=models.IntegerField(),
        ),
    ]
